### ISSUE TITLE
Create a basic map page for the homepage

### ISSUE THREAD

**Issue by MaanasArora** [CivicTechTO/tRacket-dashboard-react#3]
Use [leaflet](https://leafletjs.com/) to create a basic map page that will eventually be populated with markers individual locations in a future ticket.

**Comment by Zen-cronic** [comment]
we'd need [react-leaflet](https://react-leaflet.js.org/) as well i believe?

**Comment by MaanasArora** [comment]
@Zen-cronic Yes! I think that's a good idea.
